---
title: 'KBL: sovnprojekt'
author: "Anders Tolver"
date: "14 Dec 2017"
output:
  html_document:
    keep_md: TRUE
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Timeregnskab

* 14/12-2017: møde på Kræftens Bekæmpelse (1 t)
* 2018: indlæsning af data og organisering af projekt (4 t)
* 2018: beregning af componentscores for PSQI + CES-D (3.5 t)
* 2018: beregning af componentscores for PSQI + CES-D (3 t)
* 2018: kombiner data til samlet datasæt (1.5 t)
* 2018: midlertidigt kombineret baseline data + lang email. (1.5 t)
* 2018: opfølgning på svar på lang email (1.25 t)
* 2018: indlæsning og klargøring af data fra PSG (2 t)

# Log

## Møde d. 14/12-2017

40 patienter randomiseret til to gruppper (kontrol / intervention). Interventionsgrupper tilbydes superviseret træning på Glostrup Hospital 3 gange om ugen af en fysioterapeut. Det tilstræbes at alle deltager i 18 træningssessioner (typisk over 6-8 uger). Patienter inkluderes dog i analysen blot de har deltage i 12 træningssessioner.

Inklusionskriterie: gigtpatienter som på baggrund af en screening (hvordan?) lider af søvnproblemer. Som udgangspunkt ekskluderes patienter med søvnapnø, men på baggrund af indsamlede data viste det sig, at nogle patienter lider af søvnapnø.

Alle målinger foretages på begge patientgrupper ved baseline og post intervention 

Der foretages søvnmålinger (PSG) og der indsamles data fra patienternes søvndagbøger og en række spørgeskemaer.

2 kontrolpatienter gad ikke få lavet den sidste PSG. 

Det primære effekt mål er et standard score for søvneeffektivitet beregnet ud fra PSG.

Sekundært benyttes data fra søvndagbøger, spørgeskemaer samt en række andre mål herunder en konditest

Der er en grundlæggende opfattelse af at fysisk aktivitet påvirker søvnkvaliteten, men der er få randomiserede studier på området. Katrine har dog en artikel og fysisk aktivitet og søvn for kræftpatienter(Journal of Clinical Oncology, Savard et Al).

Der findes en protokol for studie, men der er næppe specificeret ret mange statistiske analyser.

Spørgeskemaer om: PSQI, Træthed, Depression, Fysisk aktivitet, livskvalitet, 

Katrine sender:

- anonymiseret søvnrapport (skal ikke direkte bruges til andet end orientering - danner baggrund for beregning af diverse objektive søvnmål)
- to excelark med søvnmålinger (et for baseline målinger og et for post intervention målinger)
- to excelark med baseline data og post data (hvert excel fil indeholder et større antal faneblade - en fane per skema)
- et excelark med to søjle: ID og beh.gruppe
- kopier af benyttede spørgeskemaer
- nøgleark med forklaring af variabelnavne samt angivelse af, hvilke variable der skal regnes på

Anders laver i første omgang analyse af få udvalgte variable angivet i nøglearket. Det drejer sig om

* opgørelse af mean+sd opdelt på tid x grupper
* ændringer over tid inden for gruppe (est + ki + p)
* sammeligning af ændringer over tid mellem grupper
* summaries over relevante variable, så Katrine kan kigge på det (evt spaghetti-plots)

## Kort email d. 19/3-2018

## Arbejde med data (juni 2018)

rename variable fra Anamnese som anført i KBLs nøgle.

Kvalitetskontrol og beregning af sumscorer for ESS samt BRAF skemaer.

Beregning af componentscores for PSQI.

## August 2018

Opfølgning (rensning af data) på baggrund af email d. 1/7-2018. Data fra PSG hentes omkring 2/8, hvorefter analyser påbegyndes. 

Det er stadig uklart, hvad der skal laves med data fra søvndagbøger og dette arbejde er ikke påbegyndt.

Data fra PSG udleveret på USB. PSG data oprenset og indlæst i R. 
